author = "Andy T"
baseURL = "https://bootlegninja.space/"
languageCode = "en-us"
title = "bootlegNinja.space"
disqusShortname = "bootlegninja"
googleAnalytics = "UA-87253569-1"

##[[menu.main]]
#name = "Projects"
#pre = "far fa-home"
#url = "/projects/"
#weight = 4
[[menu.main]]
name = "Blog"
pre = "far fa-pencil"
url = "/blog/"
weight = 1
[[menu.main]]
name = "Tags"
pre = "far fa-hashtag"
url = "/tags/"
weight = 2
[[menu.main]]
name = "About"
pre = "far fa-user"
url = "/about/"
weight = 3
[params]
Description = "My journal of how I'm learning to code."
dateFormat = "Jan 2, 2006"
homeText = "This is my blog of my adventures learning to build websites using Hugo and a few other tools."
[taxonomies]
tag = "tags"
author = "authors"
