author = "Andy T"
baseURL = "https://bootlegninja.space/"
languageCode = "en-us"
title = "bootlegNinja.space"
[[menu.main]]
name = "About"
pre = "user"
url = "/about/"
weight = 4
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Blog"
pre = "edit"
url = "/blog/"
weight = 2
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[params]
Description = "My journal of how I'm learning to code."
dateFormat = "Jan 2, 2006"
homeText = "This is my blog of my adventures learning to build websites using Hugo and a few other tools."
[permalinks]
blog = "/:filename/"
[taxonomies]
tag = "tags"
