author = "Andy T"
baseURL = "https://bootlegninja.space/"
languageCode = "en-us"
title = "bootlegNinja.space"
#[[menu.main]]
#name = "Authors"
#pre = "edit-2"
#url = "/authors/"
#weight = 5
[[menu.main]]
name = "About"
pre = "user"
url = "/about/"
weight = 4
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Blog"
pre = "edit"
url = "/blog/"
weight = 2
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[params]
Description = "My journal of how I'm learning to code."
dateFormat = "Jan 2, 2006"
homeText = "This is my blog of my adventures learning to build websites using Hugo and a few other tools."
google_fonts = [
  ["Fira Code", "400, 700"],
  ["Open Sans", "400, 400i, 700, 700i"]
  ]
heading_font = "Fira Code"
body_font = "Open Sans"
[taxonomies]
tag = "tags"
author = "authors"
